/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { ordersPlace } from "../../funcs/ordersPlace.js";
import * as components from "../../models/components/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: components.Order$inboundSchema.optional(),
};

export const tool$ordersPlace: ToolDefinition<typeof args> = {
  name: "orders-place",
  description: `Place an order for a pet.

Place a new order in the store.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await ordersPlace(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
