/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { ordersPlaceRaw } from "../../funcs/ordersPlaceRaw.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]).optional(),
};

export const tool$ordersPlaceRaw: ToolDefinition<typeof args> = {
  name: "orders-place-raw",
  description: `Place an order for a pet.

Place a new order in the store.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await ordersPlaceRaw(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
