/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petsDelete } from "../../funcs/petsDelete.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.DeletePetRequest$inboundSchema,
};

export const tool$petsDelete: ToolDefinition<typeof args> = {
  name: "pets-delete",
  description: `Deletes a pet.

Delete a pet.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await petsDelete(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
