/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { petsUpdateRaw } from "../../funcs/petsUpdateRaw.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]),
};

export const tool$petsUpdateRaw: ToolDefinition<typeof args> = {
  name: "pets-update-raw",
  description: `Update an existing pet.

Update an existing pet by Id.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await petsUpdateRaw(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
