/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { petsFindByStatus } from "../../funcs/petsFindByStatus.js";
import * as operations from "../../models/operations/index.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: operations.FindPetsByStatusRequest$inboundSchema,
};

export const tool$petsFindByStatus: ToolDefinition<typeof args> = {
  name: "pets-find-by-status",
  description: `Finds Pets by status.

Multiple status values can be provided with comma separated strings.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await petsFindByStatus(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
