/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { usersLogout } from "../../funcs/usersLogout.js";
import { formatResult, ToolDefinition } from "../tools.js";

export const tool$usersLogout: ToolDefinition = {
  name: "users-logout",
  description: `Logs out current logged in user session.

Log user out of the system.`,
  tool: async (client, ctx) => {
    const [result, apiCall] = await usersLogout(
      client,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    return formatResult(void 0, apiCall);
  },
};
