/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import { usersCreateRaw } from "../../funcs/usersCreateRaw.js";
import { formatResult, ToolDefinition } from "../tools.js";

const args = {
  request: z.union([
    z.instanceof(ReadableStream<Uint8Array>),
    z.instanceof(Blob),
    z.instanceof(ArrayBuffer),
    z.instanceof(Uint8Array),
  ]).optional(),
};

export const tool$usersCreateRaw: ToolDefinition<typeof args> = {
  name: "users-create-raw",
  description: `Create user.

This can only be done by the logged in user.`,
  args,
  tool: async (client, args, ctx) => {
    const [result, apiCall] = await usersCreateRaw(
      client,
      args.request,
      { fetchOptions: { signal: ctx.signal } },
    ).$inspect();

    if (!result.ok) {
      return {
        content: [{ type: "text", text: result.error.message }],
        isError: true,
      };
    }

    const value = result.value;

    return formatResult(value, apiCall);
  },
};
