/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { PetstoreCore } from "../core.js";
import { encodeBodyForm } from "../lib/encodings.js";
import * as M from "../lib/matchers.js";
import { compactMap } from "../lib/primitives.js";
import { safeParse } from "../lib/schemas.js";
import { RequestOptions } from "../lib/sdks.js";
import { extractSecurity, resolveGlobalSecurity } from "../lib/security.js";
import { pathToFunc } from "../lib/url.js";
import * as components from "../models/components/index.js";
import { APIError } from "../models/errors/apierror.js";
import {
  ConnectionError,
  InvalidRequestError,
  RequestAbortedError,
  RequestTimeoutError,
  UnexpectedClientError,
} from "../models/errors/httpclienterrors.js";
import { SDKValidationError } from "../models/errors/sdkvalidationerror.js";
import * as operations from "../models/operations/index.js";
import { APICall, APIPromise } from "../types/async.js";
import { Result } from "../types/fp.js";

export enum CreateFormAcceptEnum {
  applicationJson = "application/json",
  applicationXml = "application/xml",
}

/**
 * Create user.
 *
 * @remarks
 * This can only be done by the logged in user.
 */
export function usersCreateForm(
  client: PetstoreCore,
  request?: components.User | undefined,
  options?: RequestOptions & { acceptHeaderOverride?: CreateFormAcceptEnum },
): APIPromise<
  Result<
    operations.CreateUserFormResponse | undefined,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >
> {
  return new APIPromise($do(
    client,
    request,
    options,
  ));
}

async function $do(
  client: PetstoreCore,
  request?: components.User | undefined,
  options?: RequestOptions & { acceptHeaderOverride?: CreateFormAcceptEnum },
): Promise<
  [
    Result<
      operations.CreateUserFormResponse | undefined,
      | APIError
      | SDKValidationError
      | UnexpectedClientError
      | InvalidRequestError
      | RequestAbortedError
      | RequestTimeoutError
      | ConnectionError
    >,
    APICall,
  ]
> {
  const parsed = safeParse(
    request,
    (value) => components.User$outboundSchema.optional().parse(value),
    "Input validation failed",
  );
  if (!parsed.ok) {
    return [parsed, { status: "invalid" }];
  }
  const payload = parsed.value;

  const body = Object.entries(payload || {}).map(([k, v]) => {
    return encodeBodyForm(k, v, { charEncoding: "percent" });
  }).join("&");

  const path = pathToFunc("/user")();

  const headers = new Headers(compactMap({
    "Content-Type": "application/x-www-form-urlencoded",
    Accept: options?.acceptHeaderOverride
      || "application/json;q=1, application/xml;q=0",
  }));

  const secConfig = await extractSecurity(client._options.petstoreAuth);
  const securityInput = secConfig == null ? {} : { petstoreAuth: secConfig };
  const requestSecurity = resolveGlobalSecurity(securityInput);

  const context = {
    baseURL: options?.serverURL ?? client._baseURL ?? "",
    operationID: "createUser_form",
    oAuth2Scopes: [],

    resolvedSecurity: requestSecurity,

    securitySource: client._options.petstoreAuth,
    retryConfig: options?.retries
      || client._options.retryConfig
      || { strategy: "none" },
    retryCodes: options?.retryCodes || ["429", "500", "502", "503", "504"],
  };

  const requestRes = client._createRequest(context, {
    security: requestSecurity,
    method: "POST",
    baseURL: options?.serverURL,
    path: path,
    headers: headers,
    body: body,
    timeoutMs: options?.timeoutMs || client._options.timeoutMs || -1,
  }, options);
  if (!requestRes.ok) {
    return [requestRes, { status: "invalid" }];
  }
  const req = requestRes.value;

  const doResult = await client._do(req, {
    context,
    errorCodes: ["4XX", "5XX"],
    retryConfig: context.retryConfig,
    retryCodes: context.retryCodes,
  });
  if (!doResult.ok) {
    return [doResult, { status: "request-error", request: req }];
  }
  const response = doResult.value;

  const [result] = await M.match<
    operations.CreateUserFormResponse | undefined,
    | APIError
    | SDKValidationError
    | UnexpectedClientError
    | InvalidRequestError
    | RequestAbortedError
    | RequestTimeoutError
    | ConnectionError
  >(
    M.json(200, operations.CreateUserFormResponse$inboundSchema.optional()),
    M.bytes(200, operations.CreateUserFormResponse$inboundSchema.optional(), {
      ctype: "application/xml",
    }),
    M.fail("4XX"),
    M.fail("5XX"),
    M.nil(
      "default",
      operations.CreateUserFormResponse$inboundSchema.optional(),
    ),
  )(response);
  if (!result.ok) {
    return [result, { status: "complete", request: req, response }];
  }

  return [result, { status: "complete", request: req, response }];
}
