/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { storeGetInventory } from "../funcs/storeGetInventory.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export class Store extends ClientSDK {
  /**
   * Returns pet inventories by status.
   *
   * @remarks
   * Returns a map of status codes to quantities.
   */
  async getInventory(
    security: operations.GetInventorySecurity,
    options?: RequestOptions,
  ): Promise<{ [k: string]: number } | undefined> {
    return unwrapAsync(storeGetInventory(
      this,
      security,
      options,
    ));
  }
}
