/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import { CreateAcceptEnum, usersCreate } from "../funcs/usersCreate.js";
import {
  CreateFormAcceptEnum,
  usersCreateForm,
} from "../funcs/usersCreateForm.js";
import {
  CreateFromListAcceptEnum,
  usersCreateFromList,
} from "../funcs/usersCreateFromList.js";
import {
  CreateRawAcceptEnum,
  usersCreateRaw,
} from "../funcs/usersCreateRaw.js";
import { usersDelete } from "../funcs/usersDelete.js";
import {
  GetByNameAcceptEnum,
  usersGetByName,
} from "../funcs/usersGetByName.js";
import { LoginAcceptEnum, usersLogin } from "../funcs/usersLogin.js";
import { usersLogout } from "../funcs/usersLogout.js";
import { usersUpdate } from "../funcs/usersUpdate.js";
import { usersUpdateForm } from "../funcs/usersUpdateForm.js";
import { usersUpdateRaw } from "../funcs/usersUpdateRaw.js";
import { ClientSDK, RequestOptions } from "../lib/sdks.js";
import * as components from "../models/components/index.js";
import * as operations from "../models/operations/index.js";
import { unwrapAsync } from "../types/fp.js";

export { CreateAcceptEnum } from "../funcs/usersCreate.js";

export { CreateRawAcceptEnum } from "../funcs/usersCreateRaw.js";

export { CreateFormAcceptEnum } from "../funcs/usersCreateForm.js";

export { CreateFromListAcceptEnum } from "../funcs/usersCreateFromList.js";

export { LoginAcceptEnum } from "../funcs/usersLogin.js";

export { GetByNameAcceptEnum } from "../funcs/usersGetByName.js";

export class Users extends ClientSDK {
  /**
   * Create user.
   *
   * @remarks
   * This can only be done by the logged in user.
   */
  async create(
    request?: components.User | undefined,
    options?: RequestOptions & { acceptHeaderOverride?: CreateAcceptEnum },
  ): Promise<operations.CreateUserResponse | undefined> {
    return unwrapAsync(usersCreate(
      this,
      request,
      options,
    ));
  }

  /**
   * Create user.
   *
   * @remarks
   * This can only be done by the logged in user.
   */
  async createRaw(
    request?:
      | ReadableStream<Uint8Array>
      | Blob
      | ArrayBuffer
      | Uint8Array
      | undefined,
    options?: RequestOptions & { acceptHeaderOverride?: CreateRawAcceptEnum },
  ): Promise<operations.CreateUserRawResponse | undefined> {
    return unwrapAsync(usersCreateRaw(
      this,
      request,
      options,
    ));
  }

  /**
   * Create user.
   *
   * @remarks
   * This can only be done by the logged in user.
   */
  async createForm(
    request?: components.User | undefined,
    options?: RequestOptions & { acceptHeaderOverride?: CreateFormAcceptEnum },
  ): Promise<operations.CreateUserFormResponse | undefined> {
    return unwrapAsync(usersCreateForm(
      this,
      request,
      options,
    ));
  }

  /**
   * Creates list of users with given input array.
   *
   * @remarks
   * Creates list of users with given input array.
   */
  async createFromList(
    request?: Array<components.User> | undefined,
    options?: RequestOptions & {
      acceptHeaderOverride?: CreateFromListAcceptEnum;
    },
  ): Promise<operations.CreateUsersWithListInputResponse | undefined> {
    return unwrapAsync(usersCreateFromList(
      this,
      request,
      options,
    ));
  }

  /**
   * Logs user into the system.
   *
   * @remarks
   * Log into the system.
   */
  async login(
    request: operations.LoginUserRequest,
    options?: RequestOptions & { acceptHeaderOverride?: LoginAcceptEnum },
  ): Promise<operations.LoginUserResponse | undefined> {
    return unwrapAsync(usersLogin(
      this,
      request,
      options,
    ));
  }

  /**
   * Logs out current logged in user session.
   *
   * @remarks
   * Log user out of the system.
   */
  async logout(
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(usersLogout(
      this,
      options,
    ));
  }

  /**
   * Get user by user name.
   *
   * @remarks
   * Get user detail based on username.
   */
  async getByName(
    request: operations.GetUserByNameRequest,
    options?: RequestOptions & { acceptHeaderOverride?: GetByNameAcceptEnum },
  ): Promise<operations.GetUserByNameResponse | undefined> {
    return unwrapAsync(usersGetByName(
      this,
      request,
      options,
    ));
  }

  /**
   * Update user resource.
   *
   * @remarks
   * This can only be done by the logged in user.
   */
  async update(
    request: operations.UpdateUserRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(usersUpdate(
      this,
      request,
      options,
    ));
  }

  /**
   * Update user resource.
   *
   * @remarks
   * This can only be done by the logged in user.
   */
  async updateRaw(
    request: operations.UpdateUserRawRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(usersUpdateRaw(
      this,
      request,
      options,
    ));
  }

  /**
   * Update user resource.
   *
   * @remarks
   * This can only be done by the logged in user.
   */
  async updateForm(
    request: operations.UpdateUserFormRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(usersUpdateForm(
      this,
      request,
      options,
    ));
  }

  /**
   * Delete user resource.
   *
   * @remarks
   * This can only be done by the logged in user.
   */
  async delete(
    request: operations.DeleteUserRequest,
    options?: RequestOptions,
  ): Promise<void> {
    return unwrapAsync(usersDelete(
      this,
      request,
      options,
    ));
  }
}
