/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

/**
 * Example usage of the petstore SDK
 *
 * To run this example from the examples directory:
 * npm run build && npx tsx petsUpdate.ts
 */

import { Petstore } from "petstore";

const petstore = new Petstore({
  serverURL: "https://api.example.com",
  petstoreAuth: process.env["PETSTORE_PETSTORE_AUTH"] ?? "",
});

async function main() {
  const result = await petstore.update({
    id: 10,
    name: "doggie",
    category: {
      id: 1,
      name: "Dogs",
    },
    photoUrls: [
      "<value 1>",
    ],
  });

  console.log(result);
}

main().catch(console.error);
