/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type AddPetResponse = components.Pet | Uint8Array | string;

/** @internal */
export const AddPetResponse$inboundSchema: z.ZodType<
  AddPetResponse,
  z.ZodTypeDef,
  unknown
> = z.union([components.Pet$inboundSchema, b64$.zodInbound]);

/** @internal */
export type AddPetResponse$Outbound = components.Pet$Outbound | Uint8Array;

/** @internal */
export const AddPetResponse$outboundSchema: z.ZodType<
  AddPetResponse$Outbound,
  z.ZodTypeDef,
  AddPetResponse
> = z.union([components.Pet$outboundSchema, b64$.zodOutbound]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace AddPetResponse$ {
  /** @deprecated use `AddPetResponse$inboundSchema` instead. */
  export const inboundSchema = AddPetResponse$inboundSchema;
  /** @deprecated use `AddPetResponse$outboundSchema` instead. */
  export const outboundSchema = AddPetResponse$outboundSchema;
  /** @deprecated use `AddPetResponse$Outbound` instead. */
  export type Outbound = AddPetResponse$Outbound;
}

export function addPetResponseToJSON(addPetResponse: AddPetResponse): string {
  return JSON.stringify(AddPetResponse$outboundSchema.parse(addPetResponse));
}

export function addPetResponseFromJSON(
  jsonString: string,
): SafeParseResult<AddPetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => AddPetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'AddPetResponse' from JSON`,
  );
}
