/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateUserResponse = components.User | Uint8Array | string;

/** @internal */
export const CreateUserResponse$inboundSchema: z.ZodType<
  CreateUserResponse,
  z.ZodTypeDef,
  unknown
> = z.union([components.User$inboundSchema, b64$.zodInbound]);

/** @internal */
export type CreateUserResponse$Outbound = components.User$Outbound | Uint8Array;

/** @internal */
export const CreateUserResponse$outboundSchema: z.ZodType<
  CreateUserResponse$Outbound,
  z.ZodTypeDef,
  CreateUserResponse
> = z.union([components.User$outboundSchema, b64$.zodOutbound]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateUserResponse$ {
  /** @deprecated use `CreateUserResponse$inboundSchema` instead. */
  export const inboundSchema = CreateUserResponse$inboundSchema;
  /** @deprecated use `CreateUserResponse$outboundSchema` instead. */
  export const outboundSchema = CreateUserResponse$outboundSchema;
  /** @deprecated use `CreateUserResponse$Outbound` instead. */
  export type Outbound = CreateUserResponse$Outbound;
}

export function createUserResponseToJSON(
  createUserResponse: CreateUserResponse,
): string {
  return JSON.stringify(
    CreateUserResponse$outboundSchema.parse(createUserResponse),
  );
}

export function createUserResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateUserResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateUserResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateUserResponse' from JSON`,
  );
}
