/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type CreateUsersWithListInputResponse =
  | components.User
  | Uint8Array
  | string;

/** @internal */
export const CreateUsersWithListInputResponse$inboundSchema: z.ZodType<
  CreateUsersWithListInputResponse,
  z.ZodTypeDef,
  unknown
> = z.union([components.User$inboundSchema, b64$.zodInbound]);

/** @internal */
export type CreateUsersWithListInputResponse$Outbound =
  | components.User$Outbound
  | Uint8Array;

/** @internal */
export const CreateUsersWithListInputResponse$outboundSchema: z.ZodType<
  CreateUsersWithListInputResponse$Outbound,
  z.ZodTypeDef,
  CreateUsersWithListInputResponse
> = z.union([components.User$outboundSchema, b64$.zodOutbound]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace CreateUsersWithListInputResponse$ {
  /** @deprecated use `CreateUsersWithListInputResponse$inboundSchema` instead. */
  export const inboundSchema = CreateUsersWithListInputResponse$inboundSchema;
  /** @deprecated use `CreateUsersWithListInputResponse$outboundSchema` instead. */
  export const outboundSchema = CreateUsersWithListInputResponse$outboundSchema;
  /** @deprecated use `CreateUsersWithListInputResponse$Outbound` instead. */
  export type Outbound = CreateUsersWithListInputResponse$Outbound;
}

export function createUsersWithListInputResponseToJSON(
  createUsersWithListInputResponse: CreateUsersWithListInputResponse,
): string {
  return JSON.stringify(
    CreateUsersWithListInputResponse$outboundSchema.parse(
      createUsersWithListInputResponse,
    ),
  );
}

export function createUsersWithListInputResponseFromJSON(
  jsonString: string,
): SafeParseResult<CreateUsersWithListInputResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => CreateUsersWithListInputResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'CreateUsersWithListInputResponse' from JSON`,
  );
}
