/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type GetUserByNameRequest = {
  /**
   * The name that needs to be fetched. Use user1 for testing
   */
  username: string;
};

export type GetUserByNameResponse = components.User | Uint8Array | string;

/** @internal */
export const GetUserByNameRequest$inboundSchema: z.ZodType<
  GetUserByNameRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  username: z.string(),
});

/** @internal */
export type GetUserByNameRequest$Outbound = {
  username: string;
};

/** @internal */
export const GetUserByNameRequest$outboundSchema: z.ZodType<
  GetUserByNameRequest$Outbound,
  z.ZodTypeDef,
  GetUserByNameRequest
> = z.object({
  username: z.string(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUserByNameRequest$ {
  /** @deprecated use `GetUserByNameRequest$inboundSchema` instead. */
  export const inboundSchema = GetUserByNameRequest$inboundSchema;
  /** @deprecated use `GetUserByNameRequest$outboundSchema` instead. */
  export const outboundSchema = GetUserByNameRequest$outboundSchema;
  /** @deprecated use `GetUserByNameRequest$Outbound` instead. */
  export type Outbound = GetUserByNameRequest$Outbound;
}

export function getUserByNameRequestToJSON(
  getUserByNameRequest: GetUserByNameRequest,
): string {
  return JSON.stringify(
    GetUserByNameRequest$outboundSchema.parse(getUserByNameRequest),
  );
}

export function getUserByNameRequestFromJSON(
  jsonString: string,
): SafeParseResult<GetUserByNameRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserByNameRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserByNameRequest' from JSON`,
  );
}

/** @internal */
export const GetUserByNameResponse$inboundSchema: z.ZodType<
  GetUserByNameResponse,
  z.ZodTypeDef,
  unknown
> = z.union([components.User$inboundSchema, b64$.zodInbound]);

/** @internal */
export type GetUserByNameResponse$Outbound =
  | components.User$Outbound
  | Uint8Array;

/** @internal */
export const GetUserByNameResponse$outboundSchema: z.ZodType<
  GetUserByNameResponse$Outbound,
  z.ZodTypeDef,
  GetUserByNameResponse
> = z.union([components.User$outboundSchema, b64$.zodOutbound]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace GetUserByNameResponse$ {
  /** @deprecated use `GetUserByNameResponse$inboundSchema` instead. */
  export const inboundSchema = GetUserByNameResponse$inboundSchema;
  /** @deprecated use `GetUserByNameResponse$outboundSchema` instead. */
  export const outboundSchema = GetUserByNameResponse$outboundSchema;
  /** @deprecated use `GetUserByNameResponse$Outbound` instead. */
  export type Outbound = GetUserByNameResponse$Outbound;
}

export function getUserByNameResponseToJSON(
  getUserByNameResponse: GetUserByNameResponse,
): string {
  return JSON.stringify(
    GetUserByNameResponse$outboundSchema.parse(getUserByNameResponse),
  );
}

export function getUserByNameResponseFromJSON(
  jsonString: string,
): SafeParseResult<GetUserByNameResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => GetUserByNameResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'GetUserByNameResponse' from JSON`,
  );
}
