/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdatePetFormResponse = components.Pet | Uint8Array | string;

/** @internal */
export const UpdatePetFormResponse$inboundSchema: z.ZodType<
  UpdatePetFormResponse,
  z.ZodTypeDef,
  unknown
> = z.union([components.Pet$inboundSchema, b64$.zodInbound]);

/** @internal */
export type UpdatePetFormResponse$Outbound =
  | components.Pet$Outbound
  | Uint8Array;

/** @internal */
export const UpdatePetFormResponse$outboundSchema: z.ZodType<
  UpdatePetFormResponse$Outbound,
  z.ZodTypeDef,
  UpdatePetFormResponse
> = z.union([components.Pet$outboundSchema, b64$.zodOutbound]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdatePetFormResponse$ {
  /** @deprecated use `UpdatePetFormResponse$inboundSchema` instead. */
  export const inboundSchema = UpdatePetFormResponse$inboundSchema;
  /** @deprecated use `UpdatePetFormResponse$outboundSchema` instead. */
  export const outboundSchema = UpdatePetFormResponse$outboundSchema;
  /** @deprecated use `UpdatePetFormResponse$Outbound` instead. */
  export type Outbound = UpdatePetFormResponse$Outbound;
}

export function updatePetFormResponseToJSON(
  updatePetFormResponse: UpdatePetFormResponse,
): string {
  return JSON.stringify(
    UpdatePetFormResponse$outboundSchema.parse(updatePetFormResponse),
  );
}

export function updatePetFormResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePetFormResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePetFormResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePetFormResponse' from JSON`,
  );
}
