/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdatePetResponse = components.Pet | Uint8Array | string;

/** @internal */
export const UpdatePetResponse$inboundSchema: z.ZodType<
  UpdatePetResponse,
  z.ZodTypeDef,
  unknown
> = z.union([components.Pet$inboundSchema, b64$.zodInbound]);

/** @internal */
export type UpdatePetResponse$Outbound = components.Pet$Outbound | Uint8Array;

/** @internal */
export const UpdatePetResponse$outboundSchema: z.ZodType<
  UpdatePetResponse$Outbound,
  z.ZodTypeDef,
  UpdatePetResponse
> = z.union([components.Pet$outboundSchema, b64$.zodOutbound]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdatePetResponse$ {
  /** @deprecated use `UpdatePetResponse$inboundSchema` instead. */
  export const inboundSchema = UpdatePetResponse$inboundSchema;
  /** @deprecated use `UpdatePetResponse$outboundSchema` instead. */
  export const outboundSchema = UpdatePetResponse$outboundSchema;
  /** @deprecated use `UpdatePetResponse$Outbound` instead. */
  export type Outbound = UpdatePetResponse$Outbound;
}

export function updatePetResponseToJSON(
  updatePetResponse: UpdatePetResponse,
): string {
  return JSON.stringify(
    UpdatePetResponse$outboundSchema.parse(updatePetResponse),
  );
}

export function updatePetResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePetResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePetResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePetResponse' from JSON`,
  );
}
