/*
 * Code generated by Speakeasy (https://speakeasy.com). DO NOT EDIT.
 */

import * as z from "zod";
import * as b64$ from "../../lib/base64.js";
import { safeParse } from "../../lib/schemas.js";
import { Result as SafeParseResult } from "../../types/fp.js";
import * as components from "../components/index.js";
import { SDKValidationError } from "../errors/sdkvalidationerror.js";

export type UpdatePetWithFormRequest = {
  /**
   * ID of pet that needs to be updated
   */
  petId: number;
  /**
   * Name of pet that needs to be updated
   */
  name?: string | undefined;
  /**
   * Status of pet that needs to be updated
   */
  status?: string | undefined;
};

export type UpdatePetWithFormResponse = components.Pet | Uint8Array | string;

/** @internal */
export const UpdatePetWithFormRequest$inboundSchema: z.ZodType<
  UpdatePetWithFormRequest,
  z.ZodTypeDef,
  unknown
> = z.object({
  petId: z.number().int(),
  name: z.string().optional(),
  status: z.string().optional(),
});

/** @internal */
export type UpdatePetWithFormRequest$Outbound = {
  petId: number;
  name?: string | undefined;
  status?: string | undefined;
};

/** @internal */
export const UpdatePetWithFormRequest$outboundSchema: z.ZodType<
  UpdatePetWithFormRequest$Outbound,
  z.ZodTypeDef,
  UpdatePetWithFormRequest
> = z.object({
  petId: z.number().int(),
  name: z.string().optional(),
  status: z.string().optional(),
});

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdatePetWithFormRequest$ {
  /** @deprecated use `UpdatePetWithFormRequest$inboundSchema` instead. */
  export const inboundSchema = UpdatePetWithFormRequest$inboundSchema;
  /** @deprecated use `UpdatePetWithFormRequest$outboundSchema` instead. */
  export const outboundSchema = UpdatePetWithFormRequest$outboundSchema;
  /** @deprecated use `UpdatePetWithFormRequest$Outbound` instead. */
  export type Outbound = UpdatePetWithFormRequest$Outbound;
}

export function updatePetWithFormRequestToJSON(
  updatePetWithFormRequest: UpdatePetWithFormRequest,
): string {
  return JSON.stringify(
    UpdatePetWithFormRequest$outboundSchema.parse(updatePetWithFormRequest),
  );
}

export function updatePetWithFormRequestFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePetWithFormRequest, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePetWithFormRequest$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePetWithFormRequest' from JSON`,
  );
}

/** @internal */
export const UpdatePetWithFormResponse$inboundSchema: z.ZodType<
  UpdatePetWithFormResponse,
  z.ZodTypeDef,
  unknown
> = z.union([components.Pet$inboundSchema, b64$.zodInbound]);

/** @internal */
export type UpdatePetWithFormResponse$Outbound =
  | components.Pet$Outbound
  | Uint8Array;

/** @internal */
export const UpdatePetWithFormResponse$outboundSchema: z.ZodType<
  UpdatePetWithFormResponse$Outbound,
  z.ZodTypeDef,
  UpdatePetWithFormResponse
> = z.union([components.Pet$outboundSchema, b64$.zodOutbound]);

/**
 * @internal
 * @deprecated This namespace will be removed in future versions. Use schemas and types that are exported directly from this module.
 */
export namespace UpdatePetWithFormResponse$ {
  /** @deprecated use `UpdatePetWithFormResponse$inboundSchema` instead. */
  export const inboundSchema = UpdatePetWithFormResponse$inboundSchema;
  /** @deprecated use `UpdatePetWithFormResponse$outboundSchema` instead. */
  export const outboundSchema = UpdatePetWithFormResponse$outboundSchema;
  /** @deprecated use `UpdatePetWithFormResponse$Outbound` instead. */
  export type Outbound = UpdatePetWithFormResponse$Outbound;
}

export function updatePetWithFormResponseToJSON(
  updatePetWithFormResponse: UpdatePetWithFormResponse,
): string {
  return JSON.stringify(
    UpdatePetWithFormResponse$outboundSchema.parse(updatePetWithFormResponse),
  );
}

export function updatePetWithFormResponseFromJSON(
  jsonString: string,
): SafeParseResult<UpdatePetWithFormResponse, SDKValidationError> {
  return safeParse(
    jsonString,
    (x) => UpdatePetWithFormResponse$inboundSchema.parse(JSON.parse(x)),
    `Failed to parse 'UpdatePetWithFormResponse' from JSON`,
  );
}
