name: SDK Generation via Dispatch

on:
  repository_dispatch:
    types: [trigger-sdk-generation]

permissions:
  checks: write
  contents: write
  pull-requests: write
  statuses: write
  id-token: write

jobs:
  generate:
    uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
    with:
      force: true
      mode: pr
      set_version: ''
    secrets:
      github_access_token: ${{ secrets.GITHUB_TOKEN }}
      speakeasy_api_key: ${{ secrets.SPEAKEASY_API_KEY }}



# name: Generate

# permissions:
#   checks: write
#   contents: write
#   pull-requests: write
#   statuses: write
#   id-token: write

# on:
#   workflow_dispatch:
#     inputs:
#       force:
#         description: Force generation of SDKs
#         type: boolean
#         default: false
#       set_version:
#         description: Optionally set a specific SDK version
#         type: string
#   schedule:
#     - cron: '0 0 * * *'
#   workflow_call:  # <-- Enables reuse
#     inputs:
#       force:
#         required: false
#         type: boolean
#       set_version:
#         required: false
#         type: string
#     secrets:
#       github_access_token:
#         required: true
#       speakeasy_api_key:
#         required: true

# jobs:
#   generate:
#     uses: speakeasy-api/sdk-generation-action/.github/workflows/workflow-executor.yaml@v15
#     with:
#       force: ${{ inputs.force || false }}
#       mode: pr
#       set_version: ${{ inputs.set_version || '' }}
#     secrets:
#       github_access_token: ${{ secrets.github_access_token }}
#       speakeasy_api_key: ${{ secrets.speakeasy_api_key }}
